### ISSUE TITLE
CHEMINF fails to load with an upstream import issue

### ISSUE THREAD

**Issue by egonw** [enanomapper/ontologies#100]
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://semanticscience.org/ontology/cdk.owl> Cause: https://raw.githubusercontent.com/micheldumontier/semanticscience/master/ontology/sio/release/cdk.owl
    	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.makeLoadImportRequest(OWLOntologyManagerImpl.java:1605)
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$TPImportsHandler.handleTriple(TripleHandlers.java:1568)
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.TripleHandlers$HandlerAccessor.handleStreaming(TripleHandlers.java:200)
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer.statementWithResourceValue(OWLRDFConsumer.java:1507)
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.statementWithResourceValue(RDFParser.java:365)
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.EmptyPropertyElement.startElement(StartRDF.java:253)
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.PropertyElementList.startElement(StartRDF.java:692)
    	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParser.startElement(RDFParser.java:196)

**Comment by egonw** [comment]
@micheldumontier, the problem seems to be a redirect on the semanticscience.org website... not sure how I can fix that... suggestions?

**Comment by micheldumontier** [comment]
I can only handle these with an apache redirect. tell me which documents you need redirected?

**Comment by egonw** [comment]
Yes, that's why I asked :) What are the current rules? Because it used to work until a month ago or so... I'm trying to figure out what changed, and can then figure out what needs updating...

**Comment by micheldumontier** [comment]
I had to move the resolver to a different server, but the Apache htaccess
fike did not come with. which files do you need to resolve ?

**Comment by egonw** [comment]
At least:

    http://semanticscience.org/ontology/cdk.owl
       -> https://raw.githubusercontent.com/micheldumontier/semanticscience/master/ontology/sio/release/cdk.owl

**Comment by egonw** [comment]
OK, also these:

    http://semanticscience.org/ontology/cheminf-algorithms.owl
      -> https://raw.githubusercontent.com/semanticchemistry/semanticchemistry/master/ontology/cheminf-algorithms.owl

So, basically the same pattern, and also for these two files:

    http://semanticscience.org/ontology/cheminf-core.owl
    http://semanticscience.org/ontology/cheminf-external.owl

**Comment by micheldumontier** [comment]
done.

**Comment by egonw** [comment]
Thanks!

All is green again :) https://jenm.bigcat.maastrichtuniversity.nl/job/CHEMINF/
